// ecosystem/faucet/src/components/ui/Input.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"

const model = defineModel<string>({ required: true })

withDefaults(
  defineProps<{
    class?: string
    id?: string
    placeholder?: string
  }>(),
  {
    id: undefined,
    placeholder: undefined,
  },
)
</script>

<template>
  <input
    :id="id"
    v-model="model"
    :class="
      cn(
        'h-11 w-full rounded-lg border border-white/10 bg-slate-950/70 px-3 text-sm text-slate-50 outline-none transition placeholder:text-slate-500 focus:border-violet-400 focus:ring-3 focus:ring-violet-400/20',
        $props.class,
      )
    "
    :placeholder="placeholder"
  />
</template>

// ecosystem/wallet/components/ui/input.tsx
import * as React from "react";
import { cn } from "@/lib/utils";

export type InputProps = React.InputHTMLAttributes<HTMLInputElement>;

const Input = React.forwardRef<HTMLInputElement, InputProps>(({ className, type, ...props }, ref) => {
  return (
    <input
      type={type}
      className={cn(
        "flex h-10 w-full rounded-md border border-input bg-card px-3 py-2 text-sm outline-none transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
        className
      )}
      ref={ref}
      {...props}
    />
  );
});
Input.displayName = "Input";

export { Input };
