// ecosystem/faucet/src/components/ui/Input.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"

const model = defineModel<string>({ required: true })

withDefaults(
  defineProps<{
    class?: string
    id?: string
    placeholder?: string
  }>(),
  {
    id: undefined,
    placeholder: undefined,
  },
)
</script>

<template>
  <input
    :id="id"
    v-model="model"
    :class="
      cn(
        'h-11 w-full rounded-lg border border-white/10 bg-slate-950/70 px-3 text-sm text-slate-50 outline-none transition placeholder:text-slate-500 focus:border-violet-400 focus:ring-3 focus:ring-violet-400/20',
        $props.class,
      )
    "
    :placeholder="placeholder"
  />
</template>

// ecosystem/explorer/src/components/ui/input.tsx
import * as React from "react";
import { cn } from "@/lib/utils";

export const Input = React.forwardRef<HTMLInputElement, React.InputHTMLAttributes<HTMLInputElement>>(
  function Input({ className, ...props }, ref) {
  return (
    <input
      ref={ref}
      className={cn(
        "h-11 w-full min-w-0 rounded-lg border border-white/10 bg-white/[0.07] px-3 text-sm text-white outline-none placeholder:text-zinc-500 focus:border-violet-300 focus:ring-2 focus:ring-violet-400/30",
        className
      )}
      {...props}
    />
  );
  }
);
