// ecosystem/wallet/components/ui/badge.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const badgeVariants = cva("inline-flex items-center rounded-md border px-2 py-0.5 text-xs font-semibold", {
  variants: {
    variant: {
      default: "border-transparent bg-[linear-gradient(135deg,#2563eb,#7c3aed)] text-white",
      secondary: "border-transparent bg-secondary text-secondary-foreground",
      outline: "text-foreground",
      warning: "border-violet-200 bg-violet-50 text-violet-800 dark:border-violet-500/40 dark:bg-violet-500/15 dark:text-violet-100",
      success: "border-blue-200 bg-blue-50 text-blue-800 dark:border-blue-500/40 dark:bg-blue-500/15 dark:text-blue-100"
    }
  },
  defaultVariants: {
    variant: "default"
  }
});

export interface BadgeProps extends React.HTMLAttributes<HTMLDivElement>, VariantProps<typeof badgeVariants> {}

export function Badge({ className, variant, ...props }: BadgeProps) {
  return <div className={cn(badgeVariants({ variant }), className)} {...props} />;
}

// ecosystem/faucet/src/components/ui/Badge.vue
<script setup lang="ts">
import { computed } from "vue"

import { cn } from "@/lib/utils"

const props = withDefaults(
  defineProps<{
    class?: string
    variant?: "default" | "blue" | "violet"
  }>(),
  {
    variant: "default",
  },
)

const classes = computed(() =>
  cn(
    "inline-flex items-center rounded-md border px-2 py-1 text-xs font-medium",
    {
      "border-white/10 bg-white/[0.08] text-slate-200": props.variant === "default",
      "border-blue-400/30 bg-blue-400/10 text-blue-100": props.variant === "blue",
      "border-violet-400/30 bg-violet-400/10 text-violet-100": props.variant === "violet",
    },
    props.class,
  ),
)
</script>

<template>
  <span :class="classes">
    <slot />
  </span>
</template>
